// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func styleCSS() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `

* 
{
	color: white;
	text-shadow:1px 1px 2px white;
}

html {
	scroll-behavior: smooth;
    font-family: 'Anita Semi-Square', sans-serif;
	font-size:1.25em;
}

body, #bodycontent {
	background-color:rgb(0, 27, 39);
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    margin:0;
}

header {
    text-align: center;
    background-color:black;
}

footer {
    text-align: center;
    background-color:red;
}

main {
  flex: 1;
}

h1 {
    text-shadow: 0 0 2.5px #fff, 0 0 5px #b57cff, 0 0 10px #b57cff, 0 0 15px #b57cff, 0 0 20px #b57cff, 0 0 25px #b57cff, 0 0 35px #b57cff;
}

h2 {
    text-shadow: 0 0 2.5px #fff, 0 0 5px #64d8ff, 0 0 10px #64d8ff, 0 0 15px #64d8ff, 0 0 20px #64d8ff, 0 0 25px #64d8ff, 0 0 35px #64d8ff;
}

h3 {
    text-shadow: 0 0 2.5px #fff, 0 0 5px #66a3ff, 0 0 10px #66a3ff, 0 0 15px #66a3ff, 0 0 20px #66a3ff, 0 0 25px #66a3ff, 0 0 35px #66a3ff;
}

h4 {
    text-shadow: 0 0 2.5px #fff, 0 0 5px #8aff33, 0 0 10px #8aff33, 0 0 15px #8aff33, 0 0 20px #8aff33, 0 0 25px #8aff33, 0 0 35px #8aff33;
}


`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
