// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func loader2JS() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_loader2JS_6746`,
		Function: `function __templ_loader2JS_6746(){async function closeLoadingPage()
{
	var body = document.body;
	var sideloaders = document.getElementsByClassName("sideloader");
	setTimeout(function(){		// Wait a bit before opening because font etc.. may still not be fully loaded/rendered and it's uglys..
		body.style.overflow = "hidden"
		sideloaders[0].style.opacity = "0";
		sideloaders[0].style.transform = "scale(3)";
		sideloaders[0].style.zIndex = "-99999";
		body.style.overflow = "visible"
		console.log("loading page closed - REAAAADY !!");
	},100)
};
closeLoadingPage();
document.getElementById("bodycontent").onscroll = function() {scrollBarProgress()};
function scrollBarProgress()
{
	var winScroll = document.getElementById("bodycontent").scrollTop;
	var height = document.getElementById("bodycontent").scrollHeight - document.getElementById("bodycontent").clientHeight;
	var scrolled = (winScroll / height) * 100;
	document.getElementById("progressionBar").style.width = scrolled + "%";
}}`,
		Call:       templ.SafeScript(`__templ_loader2JS_6746`),
		CallInline: templ.SafeScriptInline(`__templ_loader2JS_6746`),
	}
}
